version: '3.9'
name: RN_MQTT

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    ports:
      - 9001:9001
      - 1883:1883